language: java
env:
  - PLAY_VERSION=2.1.1 # Latest 2.1.x
before_script:
  - wget http://downloads.typesafe.com/play/2.1.1/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip 
script: play-${PLAY_VERSION}/play test
notifications:
  email: false